### ISSUE TITLE
大佬你好，博客图片cdn出了点问题

### ISSUE THREAD

**Issue by whiplasher11** [wefantasy/FabricLearn#1]

**Comment by whiplasher11** [comment]
https://ifantasy.net/2021/07/21/setup_hyperledger_fabric_environment_and_test_demo/#%e7%8e%af%e5%a2%83%e6%90%ad%e5%bb%ba

**Comment by wefantasy** [comment]
@whiplasher11 你好，我现在检查可以访问欸，可能是之前 jsdelivr 的服务短期波动导致
